"""Video-tier odometry ablation: what each component does to the camera path and to the plan.

Every configuration runs the full video tier on the three derived videos (depth outputs are cached, so only
tracking/layout re-run). Metrics per capture: ATE of the RGB-only path vs ARKit (bench/video_odometry.py),
footprint and wall lengths vs the LiDAR plan of the same capture (bench/compare.py).

The configuration shipped as default was chosen from this table (same three captures - there is no
held-out set; disclosed in DECISIONS D22).

    python bench/video_ablation.py            # writes bench/results/video_ablation.{json,md}
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "bench"))
from compare import compare  # noqa: E402
from run_benchmark import summarise_pair  # noqa: E402
from video_odometry import evaluate as ate  # noqa: E402

CAPTURES = ["single_room", "floor_only", "with_ceiling"]
CONFIGS = [  # name, env
    ("baseline (raw depth scale)", dict(ROOMSCAN_DEPTH_SCALE="1.0", ROOMSCAN_VIDEO_MW="0", ROOMSCAN_VIDEO_GAP="0",
                                        ROOMSCAN_VIDEO_TRUST="0")),
    ("+ depth scale (leave-one-out)", dict(ROOMSCAN_VIDEO_MW="0", ROOMSCAN_VIDEO_GAP="0", ROOMSCAN_VIDEO_TRUST="0")),
    ("+ fast-turn bridging", dict(ROOMSCAN_VIDEO_MW="0", ROOMSCAN_VIDEO_GAP="1", ROOMSCAN_VIDEO_TRUST="0")),
    ("+ Manhattan rotation (lines)", dict(ROOMSCAN_VIDEO_MW="1", ROOMSCAN_VIDEO_GAP="1", ROOMSCAN_VIDEO_TRUST="0")),
    ("+ fuse trusted keyframes only", dict(ROOMSCAN_VIDEO_MW="1", ROOMSCAN_VIDEO_GAP="1", ROOMSCAN_VIDEO_TRUST="1")),
    ("+ floor-normal veto 15 deg", dict(ROOMSCAN_VIDEO_MW="1", ROOMSCAN_VIDEO_GAP="1", ROOMSCAN_VIDEO_TRUST="1",
                                       ROOMSCAN_VIDEO_VETO="15")),
]


def loo_scale(capture):
    cal = json.loads((ROOT / "bench" / "results" / "depth_calibration.json").read_text())
    return str(cal["leave_one_out_scale"][capture])


def main(out_root=ROOT / "out" / "video_ablation"):
    rows = []
    for ci, (name, env) in enumerate(CONFIGS):
        for c in CAPTURES:
            if c == "with_ceiling" and 0 < ci:
                continue      # 3.5 min walkthrough, ~30 min per run on 2 CPUs: baseline only; the shipped default
                              # configuration's with_ceiling numbers are the benchmark's video_vs_lidar row
            out = Path(out_root) / f"cfg{ci}" / c
            res_f = out / "result.json"
            e = {**os.environ, "PYTHONPATH": str(ROOT / "src"), "ROOMSCAN_DEPTH_SCALE": loo_scale(c), **env}
            if not res_f.exists():
                p = subprocess.run([sys.executable, "-m", "roomscan", str(ROOT / "data" / "tiers" / "video" / f"{c}.mp4"),
                                    "--tier", "video", "--no-damage", "--out", str(out)], env=e, cwd=ROOT,
                                   capture_output=True, text=True)
                (out / "log.txt").write_text(p.stdout + p.stderr)
                if p.returncode != 0 or not res_f.exists():
                    rows.append(dict(config=name, capture=c, failed=True))
                    print(name, c, "FAILED")
                    continue
            R = json.loads(res_f.read_text())
            L = json.loads((ROOT / "out" / "bench" / "lidar" / c / "result.json").read_text())
            a = ate(out / "work" / "trajectory.npz", ROOT / "data" / "raw" / c)["raw"]
            try:
                s = summarise_pair(compare(L, R)) if R["rooms"] else {}
            except Exception as ex:  # noqa: BLE001
                s = {"error": str(ex)}
            fp_l, fp_v = L["property"]["footprint_area"]["value"], R["property"]["footprint_area"]["value"]
            row = dict(config=name, capture=c, ate_m=a["ate_rmse_m"], ate_pct=a["ate_per_m_walked_pct"],
                       traj_scale=a["scale_factor"], rooms=len(R["rooms"]),
                       footprint_err_pct=round(100 * (fp_v - fp_l) / fp_l, 1),
                       walls=s.get("walls_compared"), wall_med_err_pct=s.get("wall_rel_err_pct_median"),
                       wall_within_8pct=s.get("wall_within_8pct"), odometry=R["capture"].get("odometry"))
            rows.append(row)
            print(json.dumps(row))
    (ROOT / "bench" / "results").mkdir(exist_ok=True)
    (ROOT / "bench" / "results" / "video_ablation.json").write_text(json.dumps(rows, indent=1))
    md = ["# Video-tier odometry ablation", "",
          "ATE = RMS camera-position error of the RGB-only path vs ARKit after rigid alignment (no scale fit).",
          "Footprint / walls vs the LiDAR plan of the same capture. Generated by `python bench/video_ablation.py`.", "",
          "| configuration | capture | ATE m | ATE % of path | rooms | footprint err % | walls | wall median err % | walls ≤8 % |",
          "|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        if r.get("failed"):
            md.append(f"| {r['config']} | {r['capture']} | failed | | | | | | |")
            continue
        md.append(f"| {r['config']} | {r['capture']} | {r['ate_m']} | {r['ate_pct']} | {r['rooms']} | "
                  f"{r['footprint_err_pct']} | {r['walls']} | {r['wall_med_err_pct']} | {r['wall_within_8pct']} |")
    common = [c for c in CAPTURES if all(any(r["config"] == n and r["capture"] == c for r in rows) for n, _ in CONFIGS)]
    md += ["", f"Means over the captures every configuration ran on ({', '.join(common)}):", "",
           "| configuration | mean ATE m | mean abs footprint err % |", "|---|---|---|"]
    for name, _ in CONFIGS:
        rs = [r for r in rows if r["config"] == name and not r.get("failed") and r["capture"] in common]
        if rs:
            md.append(f"| {name} | {np.mean([r['ate_m'] for r in rs]):.3f} | "
                      f"{np.mean([abs(r['footprint_err_pct']) for r in rs]):.1f} |")
    (ROOT / "bench" / "results" / "video_ablation.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
